services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    restart: always
    networks:
      - inception
    env_file: ./.env
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html/wordpress
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: always
    networks:
      - inception
    env_file: ./.env
    depends_on:
      - wordpress
    volumes:
      - wp_files:/var/www/html/wordpress
      - ../secrets:/etc/nginx/certs
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/alsaeed/data/mariadb_data
      o: bind
      type: none
  wp_files:
    name: wp_files
    driver: local
    driver_opts:
      device: /home/alsaeed/data/wp_files
      o: bind
      type: none